version: '3.9'

services:
  subscription_service:
    build: subscription_service
    container_name: subscription_service
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./var/logs:/logs
    
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    volumes:
       - ./var/postgres:/data/postgres
    ports:
      - "5432:5432"
    